version: '3.7'
services:
  mongodb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_USERNAME: usermongo
      MONGO_INITDB_PASSWORD: userpwd
      MONGO_INITDB_DATABASE: bootcampdb
    ports:
      - 12500:27017
    volumes:
      - ./mongo/:/etc/mongo
volumes:
  mongo: {}
      